export default class Constant {
  static CANVAS_ID = '__bigo-chart__'
  static CANDLE_INFO_CONTAINER_ID = '__candle-info__'
  static MA_INFO_CONTAINER_ID = '__MA-info__'
  static TIME_SPAN_ID = '__time-span__'
  static OPEN_SPAN_ID = '__open-span__'
  static OPEN_VALUE_ID = '__open-value__'
  static HIGH_SPAN_ID = '__high-span__'
  static HIGH_VALUE_ID = '__high-value__'
  static LOW_SPAN_ID = '__low-span__'
  static LOW_VALUE_ID = '__low-value__'
  static CLOSE_SPAN_ID = '__close-span__'
  static CLOSE_VALUE_ID = '__close-value__'
  static CHANGE_SPAN_ID = '__change-span__'
  static CHANGE_VALUE_ID = '__change-value__'
  static AMPLITUDE_SPAN_ID = '__amplitude-span__'
  static AMPLITUDE_VALUE_ID = '__amplitude-value__'
}
